# Generated by Django 5.1.4 on 2024-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(),
        ),
    ]
